"use client";
import { useEffect, useMemo, useState } from "react";

type Hazard="BRIDGE_DAMAGED"|"TRAIL_BLOCKED"|"WATER_SOURCE_DRY"|"SHELTER_UNAVAILABLE";
type Report={id:string;hazard:Hazard;note:string;status:"PENDING"|"SYNCED"};
type Friend={id:string;name:string;distance:number|null;lastSeen:string;status:"NEARBY"|"SEPARATED"|"UNKNOWN"};
type TrailParty={code:string;name:string;memberName:string;role:"ORGANIZER"|"MEMBER";createdAt:string};
type Coordinate=[number,number];
type MapPoint={id:string;type:"TRAILHEAD"|"WATER"|"SHELTER"|"DISRUPTION"|"CROSSING"|"LANDMARK"|"DESTINATION";name:string;coordinate:Coordinate;source:string;status:string};
type MapRoute={id:string;name:string;relationId:number;classification:"PREFERRED_DEMO_BASELINE"|"MAPPED_ALTERNATIVE";recommendation:string;sourceUrl:string;geometry:{type:"LineString";coordinates:Coordinate[]}};
type JourneyPack={schemaVersion:number;packId:string;trailId:string;name:string;distanceKm:number;generatedAt:string;expiresAfterHours:number;routeStatus:string;routeNotice:string;attribution:string;routes:MapRoute[];points:MapPoint[];checkpoints:{id:string;name:string;coordinate:Coordinate}[]};
type UserLocation={coordinate:Coordinate;accuracy:number};
type TrekOption={id:string;name:string;area:string;region:string;duration:string;difficulty:"Easy–moderate"|"Moderate"|"Moderate–difficult"|"Difficult";relationId?:number;packFile?:string;status:"READY"|"PLANNED";note:string};
type SignedInUser={displayName:string;email:string};

const labels:Record<Hazard,string>={BRIDGE_DAMAGED:"Bridge damaged",TRAIL_BLOCKED:"Trail blocked",WATER_SOURCE_DRY:"Water source dry",SHELTER_UNAVAILABLE:"Shelter unavailable"};
const pointLabels:Record<MapPoint["type"],string>={TRAILHEAD:"Start",WATER:"Water",SHELTER:"Shelter",DISRUPTION:"Disruption",CROSSING:"Crossing",LANDMARK:"Landmark",DESTINATION:"Destination"};
const key="raahi_reports";
const partyKey="raahi_trail_party";
const regroupKey="raahi_regroup_point";
const packKey=(trailId:string)=>trailId==="TRIUND"?"triund-current":`${trailId.toLowerCase()}-current`;
const trekOptions:TrekOption[]=[
 {id:"TRIUND",name:"Triund Trek",area:"McLeod Ganj · Dharamshala",region:"Himachal Pradesh",duration:"1–2 days",difficulty:"Easy–moderate",relationId:15522720,packFile:"/triund-pack.json",status:"READY",note:"Full Raahi demo with Exasol evidence and an offline route pack."},
 {id:"HAMPTA",name:"Hampta Pass",area:"Manali · Chatru",region:"Himachal Pradesh",duration:"4–5 days",difficulty:"Moderate",relationId:11230779,packFile:"/hampta-pack.json",status:"READY",note:"Downloadable OSM route baseline with mapped crossings and pass; field verification remains required."},
 {id:"KEDARKANTHA",name:"Kedarkantha",area:"Sankri · Govind Wildlife Sanctuary",region:"Uttarakhand",duration:"4–6 days",difficulty:"Moderate",status:"PLANNED",note:"Popular summit itinerary; winter conditions require current local guidance."},
 {id:"VALLEY_FLOWERS",name:"Valley of Flowers",area:"Govindghat · Ghangaria",region:"Uttarakhand",duration:"4–6 days",difficulty:"Moderate",status:"PLANNED",note:"Seasonal national-park trek; access and opening status must be confirmed."},
 {id:"SANDAKPHU",name:"Sandakphu–Phalut",area:"Manebhanjan · Singalila Ridge",region:"West Bengal",duration:"5–7 days",difficulty:"Moderate",status:"PLANNED",note:"Long ridge route; offline pack will include route alternatives and settlements."},
 {id:"TAWANG",name:"Tawang–Mago",area:"Tawang · Mago Valley",region:"Arunachal Pradesh",duration:"5–7 days",difficulty:"Moderate–difficult",status:"PLANNED",note:"Remote route where permits and verified local logistics are essential."},
 {id:"GOECHALA",name:"Goechala",area:"Yuksom · Kanchenjunga landscape",region:"Sikkim",duration:"8–11 days",difficulty:"Difficult",status:"PLANNED",note:"Multi-day high-altitude route; pack needs permit and seasonal-access checks."},
 {id:"KUMARA_PARVATHA",name:"Kumara Parvatha",area:"Kukke Subramanya · Pushpagiri",region:"Karnataka",duration:"2 days",difficulty:"Moderate–difficult",status:"PLANNED",note:"Western Ghats trek; entry rules and water availability need recent verification."}
];
const defaultFriends:Friend[]=[
 {id:"M01",name:"Aarav",distance:18,lastSeen:"Just now",status:"NEARBY"},
 {id:"M02",name:"Meera",distance:42,lastSeen:"1 min ago",status:"NEARBY"},
 {id:"M03",name:"Kabir",distance:null,lastSeen:"8 min ago · Forest Bend",status:"SEPARATED"}
];

function openOfflineDb(){
 return new Promise<IDBDatabase>((resolve,reject)=>{
  const request=indexedDB.open("raahi-offline",1);
  request.onupgradeneeded=()=>request.result.createObjectStore("journey-packs");
  request.onsuccess=()=>resolve(request.result);
  request.onerror=()=>reject(request.error);
 });
}

async function readPack(trailId:string){
 const db=await openOfflineDb();
 return new Promise<JourneyPack|null>((resolve,reject)=>{
  const transaction=db.transaction("journey-packs");
  const request=transaction.objectStore("journey-packs").get(packKey(trailId));
  request.onsuccess=()=>{const pack=request.result as JourneyPack|undefined;resolve(pack?.schemaVersion===2&&pack.trailId===trailId?pack:null)};
  request.onerror=()=>reject(request.error);
  transaction.oncomplete=()=>db.close();
 });
}

async function storePack(pack:JourneyPack){
 const db=await openOfflineDb();
 return new Promise<void>((resolve,reject)=>{
  const transaction=db.transaction("journey-packs","readwrite");
  transaction.objectStore("journey-packs").put(pack,packKey(pack.trailId));
  transaction.oncomplete=()=>{db.close();resolve()};
  transaction.onerror=()=>reject(transaction.error);
 });
}

function haversine(a:Coordinate,b:Coordinate){
 const toRad=(value:number)=>value*Math.PI/180;
 const dLat=toRad(b[1]-a[1]),dLon=toRad(b[0]-a[0]);
 const lat1=toRad(a[1]),lat2=toRad(b[1]);
 const h=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLon/2)**2;
 return 6371000*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h));
}

function OfflineRouteMap({pack,selectedRouteId,onRouteChange,location,onLocate}:{pack:JourneyPack;selectedRouteId:string;onRouteChange:(id:string)=>void;location:UserLocation|null;onLocate:()=>void}){
 const selectedRoute=pack.routes.find(route=>route.id===selectedRouteId)??pack.routes[0];
 const all=[...pack.routes.flatMap(route=>route.geometry.coordinates),...pack.points.map(point=>point.coordinate)];
 const lons=all.map(point=>point[0]),lats=all.map(point=>point[1]);
 const minLon=Math.min(...lons),maxLon=Math.max(...lons),minLat=Math.min(...lats),maxLat=Math.max(...lats);
 const padX=(maxLon-minLon)*.08,padY=(maxLat-minLat)*.08;
 const project=([lon,lat]:Coordinate):[number,number]=>[
  40+920*(lon-(minLon-padX))/((maxLon+padX)-(minLon-padX)),
  480-440*(lat-(minLat-padY))/((maxLat+padY)-(minLat-padY))
 ];
 const userProjected=location?project(location.coordinate):null;
 const inBounds=location&&location.coordinate[0]>=minLon-padX&&location.coordinate[0]<=maxLon+padX&&location.coordinate[1]>=minLat-padY&&location.coordinate[1]<=maxLat+padY;
 const distanceFromRoute=location?Math.min(...selectedRoute.geometry.coordinates.filter((_,index)=>index%8===0).map(point=>haversine(location.coordinate,point))):null;
 return <div className="offline-map-wrap">
  <div className="route-picker" aria-label="Mapped route alternatives">{pack.routes.map(route=><button key={route.id} className={route.id===selectedRoute.id?"selected":""} onClick={()=>onRouteChange(route.id)}><span>{route.classification==="PREFERRED_DEMO_BASELINE"?"Preferred demo route":"Mapped alternative"}</span><strong>{route.name}</strong></button>)}</div>
  <svg className="offline-map" viewBox="0 0 1000 520" role="img" aria-label={`Downloaded ${pack.name} route with traceable mapped points`}>
   <defs><linearGradient id="terrain-fill" x1="0" y1="1" x2="1" y2="0"><stop offset="0" stopColor="#bfd9c8"/><stop offset="1" stopColor="#779f88"/></linearGradient></defs>
   <rect width="1000" height="520" fill="url(#terrain-fill)"/>
   {[90,160,235,315,400].map((y,index)=><path key={y} className="map-contour" d={`M-30 ${y} C 170 ${y-65+index*7}, 290 ${y+55}, 490 ${y-5} S 800 ${y-60}, 1040 ${y+15}`}/>) }
   {pack.routes.map(route=>{const points=route.geometry.coordinates.map(point=>project(point).join(",")).join(" ");return <polyline key={route.id} className={route.id===selectedRoute.id?"route-line route-selected":"route-line route-alternative"} points={points}/>})}
   {selectedRoute.id==="GALU_TRIUND"&&pack.checkpoints.slice(1,-1).map((checkpoint,index)=>{const [x,y]=project(checkpoint.coordinate);return <g key={checkpoint.id} className="checkpoint"><circle cx={x} cy={y} r="5"/><text x={x+9} y={y-8}>{index+1}</text></g>})}
   {pack.points.map(point=>{const [x,y]=project(point.coordinate);return <g key={point.id} className={`map-pin pin-${point.type.toLowerCase()}`} transform={`translate(${x} ${y})`}><title>{point.name} · {pointLabels[point.type]} · {point.status.replaceAll("_"," ").toLowerCase()}</title><circle r={point.type==="DISRUPTION"?15:11}/><text className="pin-symbol" textAnchor="middle" y="4">{point.type==="DISRUPTION"?"!":point.type==="WATER"?"W":point.type==="SHELTER"?"S":point.type==="CROSSING"?"B":point.type==="LANDMARK"?"▲":"●"}</text><text className="pin-label" x="18" y="4">{point.name}</text></g>})}
   {userProjected&&inBounds&&<g className="user-pin" transform={`translate(${userProjected[0]} ${userProjected[1]})`}><circle className="user-pulse" r="18"/><circle r="8"/><text x="13" y="4">You</text></g>}
  </svg>
  <div className="map-status"><span className="offline-ready">✓ Available offline</span><button onClick={onLocate}>◎ {location?"Update position":"Locate me"}</button></div>
  {location&&<p className={inBounds?"location-note":"location-note location-warning"}>{inBounds?`GPS accuracy ±${Math.round(location.accuracy)} m · approximately ${Math.round(distanceFromRoute??0)} m from the route baseline`:`Your position is outside this downloaded route area · GPS accuracy ±${Math.round(location.accuracy)} m`}</p>}
  <div className="route-note"><strong>{selectedRoute.name}</strong><span>{selectedRoute.recommendation}</span><a href={selectedRoute.sourceUrl} target="_blank" rel="noreferrer">View mapped relation</a></div>
 </div>
}

export default function RaahiApp({user}:{user:SignedInUser|null}){
 const [view,setView]=useState<"journey"|"party"|"report"|"evidence">("journey");
 const [sessionStarted,setSessionStarted]=useState(Boolean(user)),[journeyStarted,setJourneyStarted]=useState(false);
 const [online,setOnline]=useState(true),[pace,setPace]=useState(71),[daylight,setDaylight]=useState(58),[battery,setBattery]=useState(16);
 const [hazard,setHazard]=useState<Hazard>("BRIDGE_DAMAGED"),[note,setNote]=useState(""),[reports,setReports]=useState<Report[]>([]),[toast,setToast]=useState("");
 const [friends,setFriends]=useState<Friend[]>(defaultFriends),[scanning,setScanning]=useState(false),[regroup,setRegroup]=useState("Forest Bend shelter");
 const [party,setParty]=useState<TrailParty|null>(null),[partyName,setPartyName]=useState("Triund trail party"),[memberName,setMemberName]=useState(user?.displayName??"Aastha"),[joinCode,setJoinCode]=useState("");
 const [pack,setPack]=useState<JourneyPack|null>(null),[packLoading,setPackLoading]=useState(false),[selectedRouteId,setSelectedRouteId]=useState("GALU_TRIUND"),[location,setLocation]=useState<UserLocation|null>(null),[selectedTrekId,setSelectedTrekId]=useState("TRIUND");
 useEffect(()=>{try{setReports(JSON.parse(localStorage.getItem(key)||"[]"));setParty(JSON.parse(localStorage.getItem(partyKey)||"null"));setRegroup(localStorage.getItem(regroupKey)||"Forest Bend shelter")}catch{}const invited=new URLSearchParams(window.location.search).get("party");if(invited)setJoinCode(invited.toUpperCase());readPack("TRIUND").then(setPack).catch(()=>undefined);if("serviceWorker" in navigator) navigator.serviceWorker.register("/sw.js").catch(()=>undefined)},[]);
 useEffect(()=>{localStorage.setItem(key,JSON.stringify(reports))},[reports]);
 useEffect(()=>{if(party)localStorage.setItem(partyKey,JSON.stringify(party));else localStorage.removeItem(partyKey)},[party]);
 useEffect(()=>{localStorage.setItem(regroupKey,regroup)},[regroup]);
 useEffect(()=>{const update=()=>setOnline(navigator.onLine);window.addEventListener("online",update);window.addEventListener("offline",update);setOnline(navigator.onLine);return()=>{window.removeEventListener("online",update);window.removeEventListener("offline",update)}},[]);
 const pending=reports.filter(r=>r.status==="PENDING").length,corroborating=2+reports.filter(r=>r.status==="SYNCED").length;
 const selectedTrek=trekOptions.find(trek=>trek.id===selectedTrekId)??trekOptions[0];
 const displayPack=pack?.schemaVersion===2&&pack.trailId===selectedTrek.id?pack:null;
 const flags=useMemo(()=>[
  daylight<90&&daylight+" min daylight buffer before shelter",
  pace<75&&pace+"% of planned pace",
  battery<20&&battery+"% battery remaining",
  corroborating>=2&&corroborating+" corroborating bridge reports"
 ].filter(Boolean) as string[],[daylight,pace,battery,corroborating]);
 async function downloadPack(){
  if(!online){setToast(displayPack?`The downloaded ${selectedTrek.name} map is ready to use offline.`:`Connect once to download the ${selectedTrek.name} journey map.`);return}
  if(!selectedTrek.packFile){setToast(`${selectedTrek.name} is available for planning, but its verified offline pack is not ready yet.`);return}
  setPackLoading(true);
  try{const response=await fetch(selectedTrek.packFile,{cache:"no-store"});if(!response.ok)throw new Error();const next=await response.json() as JourneyPack;if(next.trailId!==selectedTrek.id)throw new Error();await storePack(next);setPack(next);setSelectedRouteId(next.routes[0]?.id??"");setToast(`${selectedTrek.name} route, checkpoints and traceable mapped points are now available offline.`)}
  catch{setToast("The journey map could not be downloaded. Please try again while connected.")}
  finally{setPackLoading(false)}
 }
 function locate(){
  if(!navigator.geolocation){setToast("Location is not supported on this device.");return}
  navigator.geolocation.getCurrentPosition(position=>setLocation({coordinate:[position.coords.longitude,position.coords.latitude],accuracy:position.coords.accuracy}),()=>setToast("Location permission is needed to show your position on the offline map."),{enableHighAccuracy:true,timeout:12000,maximumAge:15000});
 }
 function save(){setReports(v=>[...v,{id:crypto.randomUUID(),hazard,note:note||labels[hazard],status:"PENDING"}]);setNote("");setToast("Saved offline. It will sync when you reconnect.")}
 function sync(){if(!online){setToast("You are offline. The report remains on this device.");return}setReports(v=>v.map(r=>({...r,status:"SYNCED"})));setToast("Reports synchronized without duplicates.")}
 function createParty(){const name=memberName.trim();if(!name){setToast("Add your name before creating a party.");return}const code=crypto.randomUUID().replaceAll("-","").slice(0,6).toUpperCase();setParty({code,name:partyName.trim()||`${selectedTrek.name} party`,memberName:name,role:"ORGANIZER",createdAt:new Date().toISOString()});setToast(`Party ${code} created and saved on this device.`)}
 function joinParty(){const code=joinCode.trim().toUpperCase().replace(/[^A-Z0-9]/g,"");const name=memberName.trim();if(code.length<4||!name){setToast("Enter your name and a valid party code.");return}setParty({code,name:`${selectedTrek.name} party`,memberName:name,role:"MEMBER",createdAt:new Date().toISOString()});setJoinCode(code);setToast(`Joined party ${code}. Membership is saved offline on this device.`)}
 async function shareParty(){if(!party)return;const url=`${window.location.origin}${window.location.pathname}?party=${party.code}`;const text=`Join my ${party.name} in Raahi with code ${party.code}`;try{if(navigator.share){await navigator.share({title:"Join my Raahi Trail Party",text,url});return}await navigator.clipboard.writeText(`${text}\n${url}`);setToast("Invite link copied. Share it before the trek while everyone has network.")}catch(error){if((error as DOMException).name!=="AbortError")setToast(`Party code: ${party.code}`)}}
 function leaveParty(){setParty(null);setFriends(defaultFriends);setToast("Trail Party removed from this device.")}
 function scanParty(){if(!party){setToast("Create or join a party first.");return}setScanning(true);setTimeout(()=>{setFriends(v=>v.map(f=>f.id==="M03"?{...f,distance:86,lastSeen:"Just spotted · simulated",status:"NEARBY"}:f));setScanning(false);setToast("Demo scan complete. Native BLE detection remains final-app scope.")},900)}
 async function chooseTrek(trek:TrekOption){setSelectedTrekId(trek.id);setLocation(null);const saved=await readPack(trek.id).catch(()=>null);setPack(saved);if(saved)setSelectedRouteId(saved.routes[0]?.id??"");setToast(saved?`${trek.name} selected. Its saved map is ready offline.`:trek.status==="READY"?`${trek.name} selected. Download its map once to use it offline.`:`${trek.name} selected for planning. Its verified offline pack is coming next.`)}
 if(!sessionStarted)return <main className="landing-page">
  <header className="landing-nav"><a className="landing-brand" href="#top" aria-label="Raahi home"><img src="/raahi-logo.png" alt=""/><span><strong>Raahi</strong><small>Offline mountain companion</small></span></a><nav aria-label="Landing navigation"><a href="#treks">Treks</a><a href="#how-it-works">How it works</a><a href="#principles">Why Raahi</a></nav><button onClick={()=>setSessionStarted(true)}>Open the demo</button></header>
  <section className="landing-hero" id="top"><div className="landing-hero-copy"><p className="eyebrow">OFFLINE JOURNEY INTELLIGENCE</p><h1>No signal.<br/>Still a plan.<br/>Still together.</h1><p>Download the route, understand what changed, and keep your trail party coordinated after connectivity disappears.</p><div className="landing-actions"><button onClick={()=>setSessionStarted(true)}>Plan a trek</button><a href="#how-it-works">See how it works</a></div></div><div className="hero-receipt"><span>Journey pack</span><strong>Ready for offline</strong><small>Routes · checkpoints · evidence · regroup point</small></div></section>
  <section className="landing-intro" id="treks"><p className="eyebrow amber">TREKS TO CARRY OFFLINE</p><h2>Choose the journey before the network chooses for you.</h2><p>Two downloadable trail baselines are ready for the demo. More routes stay hidden until their field information is verified.</p><div className="landing-trek-grid">{trekOptions.slice(0,4).map((trek,index)=><article key={trek.id} className={trek.status==="READY"?"is-ready":"is-planned"}><div className={`trek-photo trek-photo-${index+1}`}><span>{String(index+1).padStart(2,"0")}</span></div><small>{trek.region}</small><h3>{trek.name}</h3><p>{trek.area}</p><dl><div><dt>Time</dt><dd>{trek.duration}</dd></div><div><dt>Grade</dt><dd>{trek.difficulty}</dd></div></dl><button disabled={trek.status!=="READY"} onClick={()=>{setSelectedTrekId(trek.id);setSessionStarted(true)}}>{trek.status==="READY"?"Explore this trek":"Verification in progress"}</button></article>)}</div></section>
  <section className="landing-how" id="how-it-works"><div><p className="eyebrow amber">ONE JOURNEY, THREE PROMISES</p><h2>Prepared before.<br/>Informed during.<br/>Together throughout.</h2></div><ol><li><span>01</span><strong>Plan offline</strong><p>Carry route alternatives, checkpoints and important trail context on the device.</p></li><li><span>02</span><strong>Adapt with evidence</strong><p>See when pace, daylight, battery or trusted reports change the assumptions.</p></li><li><span>03</span><strong>Stay together</strong><p>Keep party context and an agreed regroup point available without network.</p></li></ol></section>
  <section className="landing-principles" id="principles"><p className="eyebrow">DESIGNED FOR THE PART WHERE SIGNAL ENDS</p><h2>A map preserves the route.<br/>Raahi preserves the plan around it.</h2><div><article><b>01</b><h3>Offline by preparation</h3><p>Every phone saves its own journey pack before the trek begins.</p></article><article><b>02</b><h3>Evidence, not promises</h3><p>Raahi explains confidence and disruption without declaring a trail safe.</p></article><article><b>03</b><h3>A fallback for people</h3><p>Trail Party keeps an offline regroup point close when friends separate.</p></article></div></section>
  <footer className="landing-footer"><img src="/raahi-logo.png" alt="Raahi"/><div><h2>Go offline without going unprepared—or alone.</h2><button onClick={()=>setSessionStarted(true)}>Enter the Raahi demo →</button></div><p>Decision support only. Follow official guidance and verified local conditions.</p></footer>
 </main>;
 if(!journeyStarted)return <main className="onboarding-shell choose-shell"><section className="choose-panel"><header className="choose-header"><div className="login-brand"><img src="/raahi-logo.png" alt="Raahi"/><div><p className="eyebrow">RAAHI</p><small>{user?`Signed in as ${user.displayName}`:"Local demo"}</small></div></div>{user?<a href="/signout-with-chatgpt?return_to=%2F">Sign out</a>:<button onClick={()=>setSessionStarted(false)}>Exit demo</button>}</header><div className="choose-title"><p className="eyebrow amber">STEP 2 OF 3</p><h1>Which trek are you planning?</h1><p>Select a trek with an available offline pack to continue to its map.</p></div><div className="onboarding-treks">{trekOptions.map(trek=>{const selected=trek.id===selectedTrekId;return <button key={trek.id} className={`${selected?"selected ":""}${trek.status==="PLANNED"?"planned":""}`} onClick={()=>trek.status==="READY"&&chooseTrek(trek)} disabled={trek.status==="PLANNED"} aria-pressed={selected}><span className="trek-choice-check">{selected?"✓":""}</span><div><small>{trek.region}</small><strong>{trek.name}</strong><p>{trek.area}</p><em>{trek.duration} · {trek.difficulty}</em></div><b>{trek.status==="READY"?"Offline map ready":"Coming soon"}</b></button>})}</div><footer className="choose-footer"><div><small>SELECTED TREK</small><strong>{selectedTrek.name}</strong><span>{selectedTrek.status==="READY"?"Route pack available":"Pack is still being verified"}</span></div><button disabled={selectedTrek.status!=="READY"} onClick={()=>setJourneyStarted(true)}>Continue to {selectedTrek.name} map →</button></footer></section></main>;
 return <main className="app-shell">
  <header className="topbar"><img className="brand-logo" src="/raahi-logo.png" alt="Raahi"/><div><p className="eyebrow">RAAHI</p><p className="subtle">{selectedTrek.name} · {displayPack?"journey map saved on this device":"offline map ready to download"}</p></div><button className="change-trek" onClick={()=>setJourneyStarted(false)}>Change trek</button><button className={online?"online-pill":"offline-pill"} onClick={()=>setOnline(v=>!v)}>● {online?"Online":"Offline"}</button></header>
  <div className="workspace-layout"><nav className="side-nav" aria-label="Main navigation"><div><p className="eyebrow">JOURNEY MENU</p><small>Keep the essentials close.</small></div>{(["journey","party","report","evidence"] as const).map((v,index)=><button key={v} className={view===v?"active":""} onClick={()=>setView(v)}><span>{String(index+1).padStart(2,"0")}</span><strong>{v==="journey"?"My journey":v==="party"?"Trail party":v==="report"?"Report a change":"Trust receipt"}</strong></button>)}<p className="side-note">Decision support only.<br/>Follow official guidance.</p></nav><div className="workspace-content">
  {view==="journey"&&<section className="hero-grid">
   <article className="map-card"><div className="map-heading"><div><p className="eyebrow">{selectedTrek.name.toUpperCase()} · {displayPack?`${displayPack.distanceKm} KM MAPPED`:selectedTrek.duration.toUpperCase()}</p><h1>{displayPack?`Explore the downloaded ${selectedTrek.name} baseline.`:`Download the ${selectedTrek.name} route pack.`}</h1></div><span className="weather">Conditions unverified</span></div>{displayPack?<OfflineRouteMap pack={displayPack} selectedRouteId={selectedRouteId} onRouteChange={setSelectedRouteId} location={location} onLocate={locate}/>:<div className="download-map"><div className="download-map-copy"><span className="download-icon">↓</span><p className="eyebrow">OFFLINE JOURNEY MAP</p><h2>Save {selectedTrek.name} before you leave.</h2><p>{selectedTrek.id==="HAMPTA"?"Download the traceable OSM hiking relation, six route checkpoints, two mapped bridge crossings and Hamta Pass. Shelters and water points are omitted until they can be verified.":"Save the mapped Triund approaches, five checkpoints, traceable shelter and water features, and the current demonstration disruption."}</p><button onClick={downloadPack} disabled={packLoading||!selectedTrek.packFile}>{packLoading?"Preparing journey map…":selectedTrek.packFile?`Download ${selectedTrek.name} map`:"Verified pack not ready"}</button><small>OpenStreetMap baseline · route and field features remain unverified until confirmed locally</small></div></div>}<div className="legend"><span><i className="safe-dot"/>Selected route</span><span><i className="alternate-dot"/>Mapped alternative</span><span><i className="risk-dot"/>Important mapped point</span>{displayPack&&<button className="refresh-pack" onClick={downloadPack} disabled={packLoading}>{packLoading?"Updating…":"Update map"}</button>}</div>{displayPack&&<div className="pack-receipt"><span><strong>{displayPack.routes.length}</strong> mapped routes</span><span><strong>{displayPack.checkpoints.length}</strong> checkpoints</span><span><strong>{displayPack.points.length}</strong> traceable points</span><a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">{displayPack.attribution}</a><p>{displayPack.routeNotice}</p></div>}</article>
   <aside className="decision-card"><p className="eyebrow amber">{selectedTrek.id==="TRIUND"?`DECISION CHECKPOINT · ${flags.length} FLAGS`:"HAMPTA EVIDENCE STATUS"}</p><h2>{selectedTrek.id==="TRIUND"?"Your original plan needs another look.":"Route downloaded. Conditions still need verification."}</h2><p className="decision-copy">{selectedTrek.id==="TRIUND"?"Exasol-driven rules saved in your offline pack detected changed assumptions.":"The Hampta pack currently contains mapped geometry only. Raahi has not verified current weather, crossings, shelters, water, permits or trail access."}</p>{selectedTrek.id==="TRIUND"?<><ul className="signal-list">{flags.map((f,i)=><li key={f}><strong>{i+1}</strong><span>{f}</span></li>)}</ul><button onClick={()=>setView("evidence")}>Review the evidence</button></>:<ul className="signal-list"><li><strong>1</strong><span>Check the Himachal trekking portal and current permit requirements</span></li><li><strong>2</strong><span>Confirm the route with a qualified local guide and recent GPX</span></li><li><strong>3</strong><span>Verify camps, water and both mapped crossings before departure</span></li></ul>}<p className="disclaimer">Decision support only. Follow official guidance and local conditions.</p></aside>
   <article className="controls-card"><label>Pace <strong>{pace}%</strong><input type="range" min="40" max="110" value={pace} onChange={e=>setPace(+e.target.value)}/></label><label>Daylight <strong>{daylight} min</strong><input type="range" min="20" max="180" value={daylight} onChange={e=>setDaylight(+e.target.value)}/></label><label>Battery <strong>{battery}%</strong><input type="range" min="5" max="100" value={battery} onChange={e=>setBattery(+e.target.value)}/></label></article>
   <section className="trek-catalog" aria-labelledby="trek-catalog-title"><div className="catalog-heading"><div><p className="eyebrow amber">CHOOSE YOUR TREK</p><h2 id="trek-catalog-title">Where are you heading?</h2></div><p>Triund and Hampta Pass now have downloadable offline baselines. Other destinations remain in planning until their routes and field points are verified.</p></div><div className="selected-trek"><span>YOUR SELECTED TREK</span><div><strong>{selectedTrek.name}</strong><small>{selectedTrek.region} · {selectedTrek.duration} · {selectedTrek.difficulty}</small></div><em>{selectedTrek.status==="READY"?"Offline map ready":"Planning mode"}</em></div><div className="trek-options">{trekOptions.map((trek,index)=>{const selected=trek.id===selectedTrekId;return <article key={trek.id} className={`trek-option${trek.status==="READY"?" ready":""}${selected?" selected":""}`}><div className="trek-card-top"><div className="trek-number">{String(index+1).padStart(2,"0")}</div><span className={trek.status==="READY"?"trek-status ready":"trek-status"}>{trek.status==="READY"?"Offline pack ready":"Pack planned"}</span></div><div><h3>{trek.name}</h3><p>{trek.area}</p><div className="trek-meta"><span>{trek.region}</span><span>{trek.duration}</span><span>{trek.difficulty}</span></div><small>{trek.note}</small></div><div className="trek-actions"><button onClick={()=>chooseTrek(trek)} aria-pressed={selected}>{selected?"Selected":"Choose trek"}</button>{trek.relationId&&<a href={`https://www.openstreetmap.org/relation/${trek.relationId}`} target="_blank" rel="noreferrer">Map source ↗</a>}</div></article>})}</div><p className="catalog-note">An offline baseline is not proof that a route is open or suitable. Before departure, use recent GPX traces and confirm routes, shelters, water points, crossings and access restrictions with authorities or a qualified local guide.</p></section>
  </section>}
  {view==="party"&&!party&&<section className="party-setup"><header><p className="eyebrow amber">TRAIL PARTY SETUP</p><h1>Connect before the signal ends.</h1><p>Create one party and share its invite code while everyone has network. Each member saves the code and regroup point locally for the trek.</p></header><div className="party-choice-grid"><article className="party-choice"><span className="party-step">01</span><h2>Create a party</h2><label className="field-label">Your name<input value={memberName} onChange={e=>setMemberName(e.target.value)} placeholder="Your name"/></label><label className="field-label">Party name<input value={partyName} onChange={e=>setPartyName(e.target.value)} placeholder="Triund trail party"/></label><button className="primary" onClick={createParty}>Create invite code</button></article><article className="party-choice"><span className="party-step">02</span><h2>Join a party</h2><label className="field-label">Your name<input value={memberName} onChange={e=>setMemberName(e.target.value)} placeholder="Your name"/></label><label className="field-label">Invite code<input value={joinCode} onChange={e=>setJoinCode(e.target.value.toUpperCase())} placeholder="ABC123" maxLength={10}/></label><button className="primary" onClick={joinParty}>Join and save offline</button></article></div><p className="prototype-note">Web-demo pairing is stored only in this browser. The final native app will verify membership through the backend and exchange rotating encrypted BLE identifiers offline.</p></section>}
  {view==="party"&&party&&<section className="panel-grid party-layout"><article className="form-card"><div className="party-session"><div><p className="eyebrow amber">{party.role==="ORGANIZER"?"PARTY ORGANIZER":"PARTY MEMBER"}</p><h1>{party.name}</h1><p>Signed in locally as <strong>{party.memberName}</strong>. Party membership and the regroup point remain available on this device offline.</p></div><div className="party-code"><small>INVITE CODE</small><strong>{party.code}</strong><span>Saved offline</span></div></div><div className="party-actions"><button className="primary" onClick={shareParty}>Share invite</button><button className="secondary" onClick={leaveParty}>Leave party</button></div><div className="party-radar" aria-label="Simulated offline friend proximity view"><span className="radar-ring ring-one"/><span className="radar-ring ring-two"/><span className="radar-you">You</span>{friends.map((f,i)=><span key={f.id} className={"radar-friend friend-"+i}>{f.name[0]}</span>)}</div><button className="primary" onClick={scanParty} disabled={scanning}>{scanning?"Running simulated proximity scan…":"Run demo proximity scan"}</button><p className="prototype-note">The invite and offline membership flow are functional. Nearby distances are simulated in this web demo; genuine background detection is reserved for the native BLE app.</p></article><aside className="queue-card"><p className="eyebrow">DEMO GROUP · {friends.length+1}</p><ul className="friend-list"><li><span><strong>{party.memberName} (you)</strong><small>This device · party {party.code}</small></span><em className="nearby">Ready</em></li>{friends.map(f=><li key={f.id}><span><strong>{f.name}</strong><small>{f.lastSeen}</small></span><em className={f.status.toLowerCase()}>{f.distance===null?"Out of range":f.distance<25?"Very close":f.distance<60?"Nearby":"Weak signal"}</em></li>)}</ul><label className="field-label">Regroup point<select value={regroup} onChange={e=>setRegroup(e.target.value)}><option>Forest Bend shelter</option><option>Magic View checkpoint</option><option>Gallu trailhead</option></select></label><div className="regroup-card"><span>Agreed regroup point</span><strong>{regroup}</strong><small>Saved locally for offline access on this device</small></div></aside></section>}
  {view==="report"&&<section className="panel-grid"><article className="form-card"><p className="eyebrow amber">COMMUNITY BREADCRUMB</p><h1>What changed?</h1><p>Reports remain on this device offline and synchronize using a unique ID.</p><div className="hazard-options">{(Object.keys(labels) as Hazard[]).map(h=><button key={h} className={hazard===h?"selected":""} onClick={()=>setHazard(h)}>{labels[h]}</button>)}</div><label className="field-label">Add an observation<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="The bridge after Forest Bend is partially damaged."/></label><button className="primary" onClick={save}>Save report offline</button></article><aside className="queue-card"><p className="eyebrow">SYNC QUEUE</p><strong className="queue-number">{pending}</strong><p>reports waiting on this device</p><button disabled={!pending} onClick={sync}>Synchronize now</button><ul>{reports.slice().reverse().map(r=><li key={r.id}><span>{labels[r.hazard]}</span><em className={r.status.toLowerCase()}>{r.status}</em></li>)}</ul></aside></section>}
  {view==="evidence"&&<section className="panel-grid"><article className="form-card"><p className="eyebrow amber">TRUST RECEIPT · FOREST BEND</p><h1>Evidence is clearer. The news is not better.</h1><div className="score-row"><div><strong>{Math.min(96,45+corroborating*13)}%</strong><span>Evidence confidence</span></div><div><strong>{Math.min(100,corroborating*40)}</strong><span>Hazard points</span></div><div><strong>{corroborating}</strong><span>Matching reports</span></div></div><p className="explanation">Independent GPS-confirmed observations agree that the bridge is damaged. Agreement increases confidence in the information while worsening the segment condition.</p></article><aside className="queue-card"><p className="eyebrow">SEGMENT CONDITION</p><div className="condition">Significant disruption</div><ul><li><span>Source</span><em>GPS-confirmed</em></li><li><span>Information age</span><em>2 hours</em></li><li><span>Fallback</span><em>Forest shelter</em></li></ul></aside></section>}
  </div></div>
  {toast&&<button className="toast" onClick={()=>setToast("")}>{toast}<span>×</span></button>}
 </main>
}
