-- Raahi / Exasol Personal schema
CREATE SCHEMA IF NOT EXISTS RAAHI;
OPEN SCHEMA RAAHI;

CREATE TABLE TRAILS (
  TRAIL_ID VARCHAR(40) PRIMARY KEY,
  NAME VARCHAR(120) NOT NULL,
  REGION VARCHAR(160),
  DISTANCE_KM DECIMAL(6,2),
  ELEVATION_GAIN_M INTEGER
);

CREATE TABLE TRAIL_SEGMENTS (
  SEGMENT_ID VARCHAR(40) PRIMARY KEY,
  TRAIL_ID VARCHAR(40) NOT NULL,
  POSITION_INDEX INTEGER NOT NULL,
  NAME VARCHAR(140) NOT NULL,
  EXPECTED_MINUTES INTEGER NOT NULL,
  IS_FALLBACK BOOLEAN DEFAULT FALSE
);

CREATE TABLE TRAVELLER_REPORTS (
  REPORT_ID VARCHAR(64) PRIMARY KEY,
  SEGMENT_ID VARCHAR(40) NOT NULL,
  HAZARD_TYPE VARCHAR(40) NOT NULL,
  SEVERITY VARCHAR(16) NOT NULL,
  DESCRIPTION VARCHAR(2000),
  SOURCE_TYPE VARCHAR(30) NOT NULL,
  OBSERVED_AT TIMESTAMP NOT NULL,
  RECEIVED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  EXPIRES_AT TIMESTAMP,
  LATITUDE DECIMAL(10,7),
  LONGITUDE DECIMAL(10,7),
  STATUS VARCHAR(20) DEFAULT 'ACTIVE'
);

CREATE TABLE SEGMENT_VERIFICATIONS (
  VERIFICATION_ID VARCHAR(64) PRIMARY KEY,
  SEGMENT_ID VARCHAR(40) NOT NULL,
  SOURCE_TYPE VARCHAR(30) NOT NULL,
  OUTCOME VARCHAR(24) NOT NULL,
  VERIFIED_AT TIMESTAMP NOT NULL
);

CREATE TABLE WEATHER_OBSERVATIONS (
  OBSERVATION_ID VARCHAR(64) PRIMARY KEY,
  TRAIL_ID VARCHAR(40) NOT NULL,
  OBSERVED_AT TIMESTAMP NOT NULL,
  PRECIPITATION_MM DECIMAL(8,2),
  CONDITION VARCHAR(40)
);

CREATE TABLE RESOURCE_POINTS (
  RESOURCE_ID VARCHAR(40) PRIMARY KEY,
  TRAIL_ID VARCHAR(40) NOT NULL,
  SEGMENT_ID VARCHAR(40),
  RESOURCE_TYPE VARCHAR(30) NOT NULL,
  NAME VARCHAR(120) NOT NULL,
  LATITUDE DECIMAL(10,7),
  LONGITUDE DECIMAL(10,7),
  LAST_VERIFIED_AT TIMESTAMP
);

CREATE TABLE DECISION_RULES (
  RULE_ID VARCHAR(50) PRIMARY KEY,
  METRIC_NAME VARCHAR(50) NOT NULL,
  OPERATOR VARCHAR(10) NOT NULL,
  THRESHOLD_VALUE DECIMAL(10,2) NOT NULL,
  SEVERITY VARCHAR(20) NOT NULL,
  MESSAGE VARCHAR(500) NOT NULL,
  ENABLED BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE VIEW SEGMENT_EVIDENCE AS
WITH ACTIVE_REPORTS AS (
  SELECT
    SEGMENT_ID,
    COUNT(*) AS ACTIVE_REPORT_COUNT,
    COUNT(DISTINCT HAZARD_TYPE) AS DISTINCT_HAZARDS,
    MAX(RECEIVED_AT) AS LAST_REPORT_AT,
    SUM(CASE HAZARD_TYPE
      WHEN 'BRIDGE_DAMAGED' THEN 40
      WHEN 'TRAIL_BLOCKED' THEN 25
      WHEN 'WATER_SOURCE_DRY' THEN 15
      WHEN 'SHELTER_UNAVAILABLE' THEN 20
      ELSE 10 END) AS HAZARD_POINTS,
    MAX(CASE SOURCE_TYPE
      WHEN 'OFFICIAL' THEN 100
      WHEN 'VERIFIED_GUIDE' THEN 85
      WHEN 'GPS_CONFIRMED' THEN 70
      ELSE 40 END) AS SOURCE_SCORE
  FROM TRAVELLER_REPORTS
  WHERE STATUS = 'ACTIVE'
    AND (EXPIRES_AT IS NULL OR EXPIRES_AT > CURRENT_TIMESTAMP)
  GROUP BY SEGMENT_ID
), VERIFICATIONS AS (
  SELECT SEGMENT_ID, MAX(VERIFIED_AT) AS LAST_VERIFIED_AT
  FROM SEGMENT_VERIFICATIONS
  GROUP BY SEGMENT_ID
)
SELECT
  S.SEGMENT_ID,
  S.TRAIL_ID,
  COALESCE(A.ACTIVE_REPORT_COUNT, 0) AS ACTIVE_REPORT_COUNT,
  LEAST(100, COALESCE(A.ACTIVE_REPORT_COUNT, 0) * 25) AS CORROBORATION_SCORE,
  COALESCE(A.SOURCE_SCORE, 40) AS SOURCE_SCORE,
  GREATEST(0, 100 - 2 * COALESCE(HOURS_BETWEEN(V.LAST_VERIFIED_AT, CURRENT_TIMESTAMP), 72)) AS RECENCY_SCORE,
  CAST(
    0.35 * GREATEST(0, 100 - 2 * COALESCE(HOURS_BETWEEN(V.LAST_VERIFIED_AT, CURRENT_TIMESTAMP), 72))
    + 0.25 * LEAST(100, COALESCE(A.ACTIVE_REPORT_COUNT, 0) * 25)
    + 0.20 * COALESCE(A.SOURCE_SCORE, 40)
    + 0.20 * CASE WHEN COALESCE(A.DISTINCT_HAZARDS, 0) <= 1 THEN 100 ELSE 50 END
    AS DECIMAL(5,2)
  ) AS EVIDENCE_CONFIDENCE,
  LEAST(100, COALESCE(A.HAZARD_POINTS, 0)) AS HAZARD_POINTS,
  CASE
    WHEN COALESCE(A.HAZARD_POINTS, 0) >= 70 THEN 'AVOID'
    WHEN COALESCE(A.HAZARD_POINTS, 0) >= 40 THEN 'DISRUPTED'
    WHEN COALESCE(A.HAZARD_POINTS, 0) >= 20 THEN 'CAUTION'
    ELSE 'NO_CURRENT_DISRUPTION'
  END AS SEGMENT_CONDITION,
  V.LAST_VERIFIED_AT
FROM TRAIL_SEGMENTS S
LEFT JOIN ACTIVE_REPORTS A ON A.SEGMENT_ID = S.SEGMENT_ID
LEFT JOIN VERIFICATIONS V ON V.SEGMENT_ID = S.SEGMENT_ID;
